package com.webservice;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2017-07-25T15:30:04.394+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "EntryPointWebServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface EntryPointWebServiceSoap {

    @WebResult(name = "GetPsMonitorResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPsMonitor", targetNamespace = "http://tempuri.org/", className = "ws.automonitor.client.GetPsMonitor")
    @WebMethod(operationName = "GetPsMonitor", action = "http://tempuri.org/GetPsMonitor")
    @ResponseWrapper(localName = "GetPsMonitorResponse", targetNamespace = "http://tempuri.org/", className = "ws.automonitor.client.GetPsMonitorResponse")
    public java.lang.String getPsMonitor(
        @WebParam(name = "url", targetNamespace = "http://tempuri.org/")
        java.lang.String url,
        @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "procName", targetNamespace = "http://tempuri.org/")
        java.lang.String procName,
        @WebParam(name = "paramJson", targetNamespace = "http://tempuri.org/")
        java.lang.String paramJson
    );

    @WebResult(name = "GetPsDataEffectiveTransferRateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPsDataEffectiveTransferRate", targetNamespace = "http://tempuri.org/", className = "ws.automonitor.client.GetPsDataEffectiveTransferRate")
    @WebMethod(operationName = "GetPsDataEffectiveTransferRate", action = "http://tempuri.org/GetPsDataEffectiveTransferRate")
    @ResponseWrapper(localName = "GetPsDataEffectiveTransferRateResponse", targetNamespace = "http://tempuri.org/", className = "ws.automonitor.client.GetPsDataEffectiveTransferRateResponse")
    public java.lang.String getPsDataEffectiveTransferRate(
        @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "procName", targetNamespace = "http://tempuri.org/")
        java.lang.String procName,
        @WebParam(name = "paramJson", targetNamespace = "http://tempuri.org/")
        java.lang.String paramJson
    );
}
