
package com.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import com.webservice.EntryPointWebService;
import com.webservice.EntryPointWebServiceSoap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2017-07-25T15:30:04.340+08:00
 * Generated source version: 2.5.9
 * 
 */
public final class EntryPointWebServiceSoap_EntryPointWebServiceSoap_Client {
	/**
	 * 日志
	 */
	private final static Logger logger = LoggerFactory.getLogger(EntryPointWebServiceSoap_EntryPointWebServiceSoap_Client.class);

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "EntryPointWebService");

    private EntryPointWebServiceSoap_EntryPointWebServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EntryPointWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	logger.info(e.getMessage());
            }
        }
      
        EntryPointWebService ss = new EntryPointWebService(wsdlURL, SERVICE_NAME);
        EntryPointWebServiceSoap port = ss.getEntryPointWebServiceSoap();
        
        {
        System.out.println("Invoking getPsMonitor...");
        java.lang.String _getPsMonitor_url = "";
        java.lang.String _getPsMonitor_key = "";
        java.lang.String _getPsMonitor_procName = "";
        java.lang.String _getPsMonitor_paramJson = "";
        java.lang.String _getPsMonitor__return = port.getPsMonitor(_getPsMonitor_url, _getPsMonitor_key, _getPsMonitor_procName, _getPsMonitor_paramJson);
        System.out.println("getPsMonitor.result=" + _getPsMonitor__return);


        }
        {
        System.out.println("Invoking getPsDataEffectiveTransferRate...");
        java.lang.String _getPsDataEffectiveTransferRate_key = "";
        java.lang.String _getPsDataEffectiveTransferRate_procName = "";
        java.lang.String _getPsDataEffectiveTransferRate_paramJson = "";
        java.lang.String _getPsDataEffectiveTransferRate__return = port.getPsDataEffectiveTransferRate(_getPsDataEffectiveTransferRate_key, _getPsDataEffectiveTransferRate_procName, _getPsDataEffectiveTransferRate_paramJson);
        System.out.println("getPsDataEffectiveTransferRate.result=" + _getPsDataEffectiveTransferRate__return);


        }

        System.exit(0);
    }

}
