package com.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.9
 * 2017-07-25T15:30:04.403+08:00
 * Generated source version: 2.5.9
 * 
 */
@WebServiceClient(name = "EntryPointWebService", 
                  wsdlLocation = "http://219.143.244.183:82/PsMonitorEntryPoint/EntryPointWebService.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/") 
public class EntryPointWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "EntryPointWebService");
    public final static QName EntryPointWebServiceSoap = new QName("http://tempuri.org/", "EntryPointWebServiceSoap");
    public final static QName EntryPointWebServiceSoap12 = new QName("http://tempuri.org/", "EntryPointWebServiceSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://219.143.244.183:82/PsMonitorEntryPoint/EntryPointWebService.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EntryPointWebService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://219.143.244.183:82/PsMonitorEntryPoint/EntryPointWebService.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EntryPointWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EntryPointWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EntryPointWebService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EntryPointWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EntryPointWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EntryPointWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EntryPointWebServiceSoap
     */
    @WebEndpoint(name = "EntryPointWebServiceSoap")
    public EntryPointWebServiceSoap getEntryPointWebServiceSoap() {
        return super.getPort(EntryPointWebServiceSoap, EntryPointWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EntryPointWebServiceSoap
     */
    @WebEndpoint(name = "EntryPointWebServiceSoap")
    public EntryPointWebServiceSoap getEntryPointWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(EntryPointWebServiceSoap, EntryPointWebServiceSoap.class, features);
    }
    /**
     *
     * @return
     *     returns EntryPointWebServiceSoap
     */
    @WebEndpoint(name = "EntryPointWebServiceSoap12")
    public EntryPointWebServiceSoap getEntryPointWebServiceSoap12() {
        return super.getPort(EntryPointWebServiceSoap12, EntryPointWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EntryPointWebServiceSoap
     */
    @WebEndpoint(name = "EntryPointWebServiceSoap12")
    public EntryPointWebServiceSoap getEntryPointWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(EntryPointWebServiceSoap12, EntryPointWebServiceSoap.class, features);
    }

}
